// src/app/layout.tsx


import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavMenu/Navbar";
import { NavAvatar } from "@/components/NavMenu/Avatar";
import Providers from "@/components/Providers"; // Import the new Providers component
import React from 'react';
import ThemeRegistry from '@/theme/Registry';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        {<script src="https://accounts.google.com/gsi/client" async></script>}

        <Providers>
          <ThemeRegistry options={{ key: 'mui' }}>
            <Navbar avatar={<NavAvatar />} />
            <div id="g_id_onload"
              data-client_id={process.env.GOOGLE_CLIENT_ID}
              data-context="signin"
              data-ux_mode="redirect"
              data-login_uri={process.env.GOOGLE_LOGIN_URI || "http://localhost:3000/api/auth/google"}
              data-callback="handleCredentialResponse" // Hier der Funktionsname
              data-itp_support="true" ></div>
            {children}
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
}