// src/app/layout.tsx


import type { Metadata } from "next";
import { Roboto, Sour_Gummy, Pacifico } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavMenu/Navbar";
import { NavAvatar } from "@/components/NavMenu/Avatar";
import Providers from "@/components/Providers"; // Import the new Providers component
import React from 'react';
import ThemeRegistry from '@/theme/Registry';


const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Sour_Gummy({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Stellen Sie diese Funktion global zur Verfügung, sodass das Google SDK sie finden kann
function handleCredentialResponse(response: CredentialResponse) {
  // `response` enthält die Anmeldedaten, die Sie an Ihren Server senden
  // um den Authentifizierungsprozess abzuschließen
  console.log("Encoded JWT ID token: " + response.credential);

  // Senden der Daten an Ihren API-Endpunkt
  fetch("https://turbo-space-parakeet-x5w5wq96jv7q36v7q-3000.app.github.dev/api/auth/callback/google", {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ credential: response.credential }),
  })
    .then(res => res.json())
    .then(data => {
      console.log('Server response:', data);
    });
}

// Fügen Sie die Funktion dem globalen Fenster-Objekt hinzu
// Dies ist der entscheidende Schritt, damit das Google-SDK die Funktion findet
if (typeof window !== 'undefined') {
  window.handleCredentialResponse = handleCredentialResponse;
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <script src="https://accounts.google.com/gsi/client" async></script>

        <Providers>
          <ThemeRegistry options={{ key: 'mui' }}>
            <Navbar avatar={<NavAvatar />} />
            <div id="g_id_onload"
              data-client_id={process.env.GOOGLE_CLIENT_ID}
              data-context="signin"
              data-ux_mode="redirect"
              data-login_uri={process.env.GOOGLE_LOGIN_URI || "https://turbo-space-parakeet-x5w5wq96jv7q36v7q-3000.app.github.dev/api/auth/google"}
              data-callback="handleCredentialResponse" // Hier der Funktionsname
              data-itp_support="true" />
            {children}
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
}